title : University of Oklahoma API

markdown: kramdown

safe: true
lsi: false
pygments: true
auto: true

source: university-of-oklahoma-api
destination: university-of-oklahoma-api

permalink: /:categories/:year/:month/:day/:title 
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 1000
paginate_path: "/blog/page:num"

production_url : http://university-of-oklahoma-api.apievangelist.com

BASE_PATH : http://university-of-oklahoma-api.apievangelist.com

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
